//
//  HostTabBarPresenter.swift
//  ExchangeHelper
//
//  Created by browen on 2019/05/02.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HostTabBarPresentationLogic {
  func presentSomething(response: HostTabBar.Something.Response)
}

class HostTabBarPresenter: HostTabBarPresentationLogic {
  weak var viewController: HostTabBarDisplayLogic?

  // MARK: Do something

  func presentSomething(response: HostTabBar.Something.Response) {
    let viewModel = HostTabBar.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
