//
//  HostTabBarWorker.swift
//  ExchangeHelper
//
//  Created by Meiliang Wen on 25/01/2018.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HostTabBarWorker {
  func doSomeWork() {
  }
}
