//
//  HostTabBarRouter.swift
//  ExchangeHelper
//
//  Created by browen on 2019/05/02.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HostTabBarRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol HostTabBarDataPassing {
  var dataStore: HostTabBarDataStore? { get }
}

class HostTabBarRouter: NSObject, HostTabBarRoutingLogic, HostTabBarDataPassing {
  weak var viewController: HostTabBarController?
  var dataStore: HostTabBarDataStore?
}
