//
//  HostTabBarRouter.swift
//  CURRENCY
//
//  Created by Stan Liu on 25/01/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HostTabBarRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol HostTabBarDataPassing {
  var dataStore: HostTabBarDataStore? { get }
}

class HostTabBarRouter: NSObject, HostTabBarRoutingLogic, HostTabBarDataPassing {
  weak var viewController: HostTabBarController?
  var dataStore: HostTabBarDataStore?

  // MARK: Routing

  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation

  //func navigateToSomewhere(source: HostTabBarViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}

  // MARK: Passing data

  //func passDataToSomewhere(source: HostTabBarDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
