//
//  ShowFullAdsPresenter.swift
//  CURRENCY
//
//  Created by curry on 2019/04/29.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowFullAdsPresentationLogic {
  func presentSomething(response: ShowFullAds.Something.Response)
}

class ShowFullAdsPresenter: ShowFullAdsPresentationLogic {
  weak var viewController: ShowFullAdsDisplayLogic?

  // MARK: Do something

  func presentSomething(response: ShowFullAds.Something.Response) {
    let viewModel = ShowFullAds.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
