//
//  ShowFullAdsWorker.swift
//  CURRENCY
//
//  Created by curry on 2019/04/29.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ShowFullAdsWorker {
  func doSomeWork() {
  }
}
