//
//  ShowFullAdsRouter.swift
//  CURRENCY
//
//  Created by Stan Liu on 22/02/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowFullAdsRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ShowFullAdsDataPassing {
  var dataStore: ShowFullAdsDataStore? { get }
}

class ShowFullAdsRouter: NSObject, ShowFullAdsRoutingLogic, ShowFullAdsDataPassing {
  weak var viewController: ShowFullAdsViewController?
  var dataStore: ShowFullAdsDataStore?

  // MARK: Routing

  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation

  //func navigateToSomewhere(source: ShowFullAdsViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}

  // MARK: Passing data

  //func passDataToSomewhere(source: ShowFullAdsDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
