//
//  ShowFullAdsInteractor.swift
//  CURRENCY
//
//  Created by curry on 2019/04/29.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowFullAdsBusinessLogic {
  func doSomething(request: ShowFullAds.Something.Request)
}

protocol ShowFullAdsDataStore {
  //var name: String { get set }
}

class ShowFullAdsInteractor: ShowFullAdsBusinessLogic, ShowFullAdsDataStore {
  var presenter: ShowFullAdsPresentationLogic?
  var worker: ShowFullAdsWorker?
  //var name: String = ""

  // MARK: Do something

  func doSomething(request: ShowFullAds.Something.Request) {
    worker = ShowFullAdsWorker()
    worker?.doSomeWork()

    let response = ShowFullAds.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
