//
//  ListSettingInteractor.swift
//  ExchangeHelper
//
//  Created by Meiliang Wen on 22/02/2018.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoreBusinessLogic {
  func fetchSettings(request: ListMore.Fetch.Request)
}

protocol ListMoreDataStore {
  var settings: [Setting]? { get }
}

class ListMoreInteractor: ListMoreBusinessLogic, ListMoreDataStore {
  var presenter: ListMorePresentationLogic?
  var worker: ListMoreWorker?

  var settings: [Setting]?

  // MARK: Fetch settings

  func fetchSettings(request: ListMore.Fetch.Request) {
    self.settings = APPSetting.settings
    let response = ListMore.Fetch.Response(settings: settings)
    presenter?.presentFetchedSettings(response: response)
  }
}
