//
//  ListSettingPresenter.swift
//  CURRENCY
//
//  Created by Stan Liu on 22/02/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMorePresentationLogic {
  func presentFetchedSettings(response: ListMore.Fetch.Response)
}

class ListMorePresenter: ListMorePresentationLogic {
  weak var viewController: ListMoreDisplayLogic?

  // MARK: Do something

  func presentFetchedSettings(response: ListMore.Fetch.Response) {
    let viewModel = ListMore.Fetch.ViewModel(settings: response.settings)
    viewController?.displayFetchedSettings(viewModel: viewModel)
  }
}
