//
//  ListSettingModels.swift
//  CURRENCY
//
//  Created by Stan Liu on 22/02/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListMore {
  // MARK: Use cases

  enum Fetch {
    struct Request {
    }
    struct Response {
      var settings: [Setting]?
    }
    struct ViewModel {
      var settings: [Setting]?
    }
  }
}
