//
//  SelectSettingRouter.swift
//  CURRENCY
//
//  Created by Stan Liu on 24/02/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SelectSettingRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SelectSettingDataPassing {
  var dataStore: SelectSettingDataStore? { get }
}

class SelectSettingRouter: NSObject, SelectSettingRoutingLogic, SelectSettingDataPassing {
  weak var viewController: SelectSettingViewController?
  var dataStore: SelectSettingDataStore?

  // MARK: Routing

  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation

  //func navigateToSomewhere(source: SelectSettingViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}

  // MARK: Passing data

  //func passDataToSomewhere(source: SelectSettingDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
