//
//  SelectSettingModels.swift
//  CURRENCY
//
//  Created by Stan Liu on 24/02/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SelectSetting {
  // MARK: Use cases

  enum FetchTitle {
    struct Request {
    }
    struct Response {
      var titleLocalizedKey: String
    }
    struct ViewModel {
      var displayTitle: String
    }
  }

  enum FetchSetting {
    struct Request {
    }
    struct Response {
      var setting: Setting
    }
    struct ViewModel {
      var applyConfigurationHandler: ((String?) -> Void)?
      var optionKeys: [String]
      var optionValues: [String]
      var currentOption: String
    }
  }

  enum Select {
    struct Request {
      var chosen: String
    }
    struct Response {
      var chosen: String
    }
    struct ViewModel {
      var chosen: String
    }
  }
}
