//
//  ChartInteractor.swift
//  ExchangeHelper
//
//  Created by Meiliang Wen on 28/03/2018.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartBusinessLogic {
  func fetchCurrencyHistory(request: Chart.Fetch.Request)
}

protocol ChartDataStore {
}

class ChartInteractor: ChartBusinessLogic, ChartDataStore {
  var presenter: ChartPresentationLogic?
  var worker: ChartWorker?

  // MARK: Fetch currency history

  func fetchCurrencyHistory(request: Chart.Fetch.Request) {
    worker = ChartWorker()
    worker?.doSomeWork()

    let response = Chart.Fetch.Response()
    presenter?.presentFetchedHistory(response: response)
  }
}
