//
//  ChartRouter.swift
//  CURRENCY
//
//  Created by Stan Liu on 28/03/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChartRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  func routeToChartViewController()
}

protocol ChartDataPassing {
  var dataStore: ChartDataStore? { get }
}

class ChartRouter: NSObject, ChartRoutingLogic, ChartDataPassing {
  weak var viewController: ChartViewController?
  var dataStore: ChartDataStore?

  // MARK: Routing

  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  func routeToChartViewController() {
    guard let destinationVC = R.storyboard.bankCurrency.chartViewController(),
      var destinationDS = destinationVC.router?.dataStore,
      let sourceVC = viewController,
      let sourceDS = dataStore else { return }
    passDataToChart(source: sourceDS, destination: &destinationDS)
    navigateToChart(source: sourceVC, destination: destinationVC)
  }
  // MARK: Navigation

  //func navigateToSomewhere(source: ChartViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  func navigateToChart(source: ChartViewController, destination: ChartViewController) {
    source.present(destination, animated: true, completion: nil)
  }

  // MARK: Passing data

  //func passDataToSomewhere(source: ChartDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
  func passDataToChart(source: ChartDataStore, destination: inout ChartDataStore) {
  }
}
