//
//  ChartModels.swift
//  ExchangeHelper
//
//  Created by mike on 2019/05/01.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Chart {

  enum Heroing {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
  enum Fetch {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
}
