//
//  EditConvertCurrencyWorker.swift
//  ExchangeHelper
//
//  Created by smith on 2019/04/24.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EditConvertCurrencyWorker {

//  func loadAllCurrencies() -> [String] {
//    return ["USD", "TWD", "JPY", "AUD", "CAD", "HKD", "NZD", "EUR", "KRW", "IDR", "PHP"]
//  }
//
//  func loadFavoriteCurrencies() -> [String] {
//    return UserSettings.favoriteCurrencies()
//  }
}
