//
//  EditConvertCurrencyWorker.swift
//  CURRENCY
//
//  Created by Stan Liu on 09/02/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EditConvertCurrencyWorker {

//  func loadAllCurrencies() -> [String] {
//    return ["USD", "TWD", "JPY", "AUD", "CAD", "HKD", "NZD", "EUR", "KRW", "IDR", "PHP"]
//  }
//
//  func loadFavoriteCurrencies() -> [String] {
//    return UserSettings.favoriteCurrencies()
//  }
}
