//
//  EditConvertCurrencyInteractor.swift
//  ExchangeHelper
//
//  Created by Meiliang Wen on 09/02/2018.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditConvertCurrencyBusinessLogic {
  func fetchBankCurrencies(request: EditConvertCurrency.Favorites.Request)
  func toggleFavoriteCurrencies(request: EditConvertCurrency.Update.Request)
}

protocol EditConvertCurrencyDataStore {
  var listCurrencyVC: ConvertCurrencyViewController? { get set }
  var currencies: [EditConvertCurrency.Favorites.Response.FavoriteCurrency] { get set }
}

class EditConvertCurrencyInteractor: EditConvertCurrencyBusinessLogic, EditConvertCurrencyDataStore {
  var presenter: EditConvertCurrencyPresentationLogic?
  var worker: EditConvertCurrencyWorker?

  // For router
  weak var listCurrencyVC: ConvertCurrencyViewController?
  var currencies: [EditConvertCurrency.Favorites.Response.FavoriteCurrency] = []

  // MARK: Fetch
  func fetchBankCurrencies(request: EditConvertCurrency.Favorites.Request) {
    let currs = currencies.map {
      return EditConvertCurrency.Favorites.Response.FavoriteCurrency(name: $0.name,
                                                                     isFavored: $0.isFavored)
    }
    self.currencies = currs
    let response = EditConvertCurrency.Favorites.Response(currencies: currs)
    presenter?.presentBankCurrencies(response: response)
  }

  func toggleFavoriteCurrencies(request: EditConvertCurrency.Update.Request) {
    let currs = currencies.map { (object) -> EditConvertCurrency.Favorites.Response.FavoriteCurrency in
      var copied = object
      guard copied.name == request.name else {
        return copied
      }
      copied.isFavored = !object.isFavored
      return copied
    }
    self.currencies = currs
    let response = EditConvertCurrency.Update.Response(indexPath: request.indexPath,
                                                       currencies: currs)
    presenter?.presentToggledFavoriteCurrencies(response: response)
  }
}
