//
//  EditConvertCurrencyPresenter.swift
//  ExchangeHelper
//
//  Created by smith on 2019/04/24.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditConvertCurrencyPresentationLogic {
  func presentBankCurrencies(response: EditConvertCurrency.Favorites.Response)
  func presentToggledFavoriteCurrencies(response: EditConvertCurrency.Update.Response)
}

class EditConvertCurrencyPresenter: EditConvertCurrencyPresentationLogic {
  weak var viewController: EditConvertCurrencyDisplayLogic?

  // MARK: Do something
  func presentBankCurrencies(response: EditConvertCurrency.Favorites.Response) {
    let displayCurrencies = response.currencies.map {
      return EditConvertCurrency.Favorites.ViewModel.DisplayCurrency(name: $0.name,
                                                                  isFavored: $0.isFavored)
    }
    let viewModel = EditConvertCurrency.Favorites.ViewModel(displayCurrencies: displayCurrencies)
    viewController?.displayBankCurrencies(viewModel: viewModel)
  }

  func presentToggledFavoriteCurrencies(response: EditConvertCurrency.Update.Response) {
    let displayCurrencies = response.currencies.map {
      return EditConvertCurrency.Favorites.ViewModel.DisplayCurrency(name: $0.name,
                                                                   isFavored: $0.isFavored)
    }
    let viewModel = EditConvertCurrency.Update.ViewModel(indexPath: response.indexPath,
                                                       displayCurrencies: displayCurrencies)
    viewController?.displayToggledFavoriteCurrencies(viewModel: viewModel)
  }
}
