//
//  ListBankCurrencyRouter.swift
//  ExchangeHelper
//
//  Created by wang on 2019/04/24.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListBankCurrencyRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  func routeToUpdateBankCurrency()
}

protocol ListBankCurrencyDataPassing {
  var dataStore: ListBankCurrencyDataStore? { get }
}

class ListBankCurrencyRouter: NSObject, ListBankCurrencyRoutingLogic, ListBankCurrencyDataPassing {
  weak var viewController: ListBankCurrencyViewController?
  var dataStore: ListBankCurrencyDataStore?

  // MARK: Routing
  func routeToUpdateBankCurrency() {
    if let sourceDS = dataStore,
      let destinationVC = sourceDS.parentVC,
      var destinationDS = destinationVC.router?.dataStore {
      passDataToBankCurrency(source: sourceDS, destination: &destinationDS)
    }
  }


  // MARK: Passing data

  func passDataToBankCurrency(source: ListBankCurrencyDataStore, destination: inout BankCurrencyDataStore) {
    source.exchange == .cash
      ? (destination.cash = source.bank)
      : (destination.stock = source.bank)
  }
}
