//
//  ListBankCurrencyModels.swift
//  ExchangeHelper
//
//  Created by Meiliang Wen on 27/03/2018.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListBankCurrency {
  // MARK: Use cases

  enum FetchCurrencyList {
    struct Request {
    }
    struct Response {
      var bank: BankCurrency.Bank
    }
    struct ViewModel {
      var displayBank: BankCurrency.Fetch.DisplayBank
      var displayNameMaxWidth: CGFloat
    }
  }

  enum Update {
    struct Request {
      var index: Int?
      var histories: [HistoryModelize]?
      var chartImage: UIImage?
    }
    struct Resopnse {
    }
    struct ViewModel {
    }
  }

  enum FetchCurrencyChartImage {
    struct Request {
      var subject: String
      var indexPath: IndexPath
    }
    struct Response {
      var rates: [String]
      var chartImage: UIImage
      var indexPath: IndexPath
    }
    struct ViewModel {
      var displayRates: [String]
      var displayChartImage: UIImage
      var indexPath: IndexPath
    }
  }
}
