//
//  TWBankPresenter.swift
//  CURRENCY
//
//  Created by Stan Liu on 22/03/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TWBankPresentationLogic {
  func presentTitle(response: TWBank.Title.Response)
  func presentFetchedTWBanksSpecificCurrency(response: TWBank.Fetch.Response)
  func presentError(response: Base.HandleError.Response)
}

class TWBankPresenter: TWBankPresentationLogic {
  weak var viewController: TWBankDisplayLogic?

  // MARK: Do something
  func presentTitle(response: TWBank.Title.Response) {
    let viewModel = TWBank.Title.ViewModel(title: response.title)
    viewController?.displayTitle(viewModel: viewModel)
  }

  func presentFetchedTWBanksSpecificCurrency(response: TWBank.Fetch.Response) {
    let viewModel = TWBank.Fetch.ViewModel(exchangeType: response.exchangeType)
    viewController?.displayFetchedTWBanksSpecificCurrency(viewModel: viewModel)
  }

  func presentError(response: Base.HandleError.Response) {
    let viewModel = Base.HandleError.ViewModel(error: response.error)
    viewController?.displayError(viewModel: viewModel)
  }
}
