//
//  TWBankRouter.swift
//  CURRENCY
//
//  Created by Stan Liu on 22/03/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TWBankRoutingLogic {
  func routeToStock(destination: ListBankViewController)
  func routeToCash(destination: ListBankViewController)
}

protocol TWBankDataPassing {
  var dataStore: TWBankDataStore? { get }
}

class TWBankRouter: NSObject, TWBankRoutingLogic, TWBankDataPassing {
  weak var viewController: TWBankViewController?
  var dataStore: TWBankDataStore?

  // MARK: Routing

  //func routeToListBank(segue: UIStoryboardSegue?) {
  //if let segue = segue {
  //  let destinationVC = segue.destination as! SomewhereViewController
  //  var destinationDS = destinationVC.router!.dataStore!
  //  passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //} else {
  //  let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //  let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //  var destinationDS = destinationVC.router!.dataStore!
  //  passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  navigateToSomewhere(source: viewController!, destination: destinationVC)
  //}
  //}

  func routeToStock(destination: ListBankViewController) {
    guard
      let sourceDS = dataStore,
      var destinationDS = destination.router?.dataStore
      else { return }
    passDataToListBank(exchange: .stock,
                          source: sourceDS,
                          destination: &destinationDS)
    destination.showList()
  }

  func routeToCash(destination: ListBankViewController) {
    guard
      let sourceDS = dataStore,
      var destinationDS = destination.router?.dataStore
      else { return }
    passDataToListBank(exchange: .cash,
                          source: sourceDS,
                          destination: &destinationDS)
    destination.showList()
  }

  // MARK: Navigation

  //func navigateToSomewhere(source: TWBankViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}

  // MARK: Passing data

  func passDataToListBank(exchange: ExchangeType,
                          source: TWBankDataStore,
                          destination: inout ListBankDataStore) {
    destination.banks = exchange == .cash
      ? source.banksOfCash
      : source.banksOfStock
  }
}
