//
//  CURRENCY
//
//  Created by Stan Liu on 22/03/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TWBankWorker {
  func fetch(subject: String,
             exchange: ExchangeType,
             completion: @escaping ([RterBank<RterCurrency>], Error?) -> Void) {
    API().highestCurrencyOfBanks(source: .rter(.currency(subject), exchange)) { (banks, error) in
      guard let banks = banks,
        error == nil else {
        completion([], error)
        return
      }
      completion(banks, nil)
    }
  }
}
