//
//  TWBankModels.swift
//  ExchangeHelper
//
//  Created by Meiliang Wen on 22/03/2018.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TWBank {

  struct Bank: BankBasic, CarryFee, CarryImageURL {
    var name: String
    var swiftCode: String
    var fee: String
    var imageURL: String?
    var currency: Currency
  }
  struct Currency: CurrencyBasic, CarryLastUpdate, CarryImageURL {
    var name: String
    var buy: String
    var sell: String
    var lastUpdate: String
    var imageURL: String?
  }

  enum Title {
    struct Request { }
    struct Response {
      var title: String
    }
    struct ViewModel {
      var title: String
    }
  }

  enum Fetch {
    struct Request {
      var exchangeType: ExchangeType
    }
    struct Response {
      var exchangeType: ExchangeType
    }
    struct ViewModel {
      var exchangeType: ExchangeType
    }
  }
}
