//
//  BankCurrencyWorker.swift
//  ExchangeHelper
//
//  Created by mary on 2019/05/02.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BankCurrencyWorker {
  func fetch(rter: Rter,
             exchange: ExchangeType,
             completion: @escaping (RterBank<[RterCurrency]>?, Error?) -> Void) {
    APIService().currenciesOfBank(source: Source.rter(rter, exchange)) { (bank, error) in
      completion(bank, error)
    }
  }
}
