//
//  BankCurrencyPresenter.swift
//  ExchangeHelper
//
//  Created by mary on 2019/05/02.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BankCurrencyPresentationLogic {
  func presentFetchedBankCurrencies(response: BankCurrency.Fetch.Response)
  func presentError(response: Base.HandleError.Response)
}

class BankCurrencyPresenter: BankCurrencyPresentationLogic {
  weak var viewController: BankCurrencyDisplayLogic?

  // MARK: Do something

  func presentFetchedBankCurrencies(response: BankCurrency.Fetch.Response) {

    let displayBank = BankCurrency.Fetch.DisplayBank(name: response.bank.name,
                                                     swiftCode: response.bank.swiftCode,
                                                     fee: response.bank.fee,
                                                     imageURL: response.bank.imageURL,
                                                     currencies: response.bank.currencies.map {
                                                      return BankCurrency.Fetch.DisplayCurrency(name: $0.name,
                                                                                                buy: $0.buy,
                                                                                                sell: $0.sell,
                                                                                                lastUpdate: $0.lastUpdate,
                                                                                                imageURL: $0.imageURL,
                                                                                                histories: $0.histories,
                                                                                                chartImage: $0.chartImage)
    })
    let viewModel = BankCurrency.Fetch.ViewModel(exchangeType: response.exchangeType, displayBank: displayBank)
    viewController?.displayFetchedBankCurrencies(viewModel: viewModel)
  }

  func presentError(response: Base.HandleError.Response) {
    let viewModel = Base.HandleError.ViewModel(error: response.error)
    viewController?.displayError(viewModel: viewModel)
  }
}
