//
//  ConvertCurrencyRouter.swift
//  ExchangeHelper
//
//  Created by curry on 2019/04/30.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ConvertCurrencyRoutingLogic {
  func routeToEditConvertCurrency(segue: UIStoryboardSegue?)
}

protocol ConvertCurrencyDataPassing {
  var dataStore: ConvertCurrencyDataStore? { get }
}

class ConvertCurrencyRouter: NSObject, ConvertCurrencyRoutingLogic, ConvertCurrencyDataPassing {
  weak var viewController: ConvertCurrencyViewController?
  var dataStore: ConvertCurrencyDataStore?

  // MARK: Routing

  func routeToEditConvertCurrency(segue: UIStoryboardSegue?) {
    guard let destinationVC = R.storyboard.convertCurrency.editConvertCurrencyViewController(),
      let dataStore = dataStore,
      let viewController = viewController,
      var destinationDS = destinationVC.router?.dataStore else {
        return
    }
    passDataToEditConvertCurrency(source: dataStore, destination: &destinationDS)
    navigateToEditConvertCurrency(source: viewController, destination: destinationVC)
  }

  // MARK: Navigation

  func navigateToEditConvertCurrency(source: ConvertCurrencyViewController,
                                     destination: EditConvertCurrencyViewController) {
    source.present(destination, animated: true, completion: nil)
  }

  // MARK: Passing data

  func passDataToEditConvertCurrency(source: ConvertCurrencyDataStore,
                                     destination: inout EditConvertCurrencyDataStore) {
    destination.listCurrencyVC = viewController
    destination.currencies = APPSetting.Preference.currency.options.map {
      if source.favoriteCurrencyNameList.contains($0) {
        return EditConvertCurrency.Favorites.Response.FavoriteCurrency(name: $0, isFavored: true)
      } else {
        return EditConvertCurrency.Favorites.Response.FavoriteCurrency(name: $0, isFavored: false)
      }
    }
  }
}
