//
//  ListCurrencyViewController.swift
//  CURRENCY
//
//  Created by curry on 2019/04/30.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCurrencyDisplayLogic: class {
  func displaySomething(viewModel: ListCurrency.Something.ViewModel)
}

class ListCurrencyViewController: UIViewController, ListCurrencyDisplayLogic, UITableViewDelegate, UITableViewDataSource {
  var interactor: ListCurrencyBusinessLogic?
  var router: (NSObjectProtocol & ListCurrencyRoutingLogic & ListCurrencyDataPassing)?

  // MARK: Object lifecycle
  @IBOutlet weak var tableView: UITableView!

  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }

  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }

  // MARK: Setup

  private func setup() {
    let viewController = self
    let interactor = ListCurrencyInteractor()
    let presenter = ListCurrencyPresenter()
    let router = ListCurrencyRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }

  // MARK: Routing

  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }

  // MARK: View lifecycle

  override func viewDidLoad() {
    super.viewDidLoad()
    configureTableView()
    doSomething()
  }

  func configureTableView() {
    tableView.delegate = self
    tableView.dataSource = self
  }

  // MARK: Do something

  //@IBOutlet weak var nameTextField: UITextField!

  func doSomething() {
    let request = ListCurrency.Something.Request()
    interactor?.doSomething(request: request)
  }

  func displaySomething(viewModel: ListCurrency.Something.ViewModel) {
    //nameTextField.text = viewModel.name
  }

  // MARK: UITableViewDelegate

  func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
  }

  // MARK: UITableViewDataSource

  func numberOfSections(in tableView: UITableView) -> Int {
    return 1
  }

  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return 1
 }

  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
   return UITableViewCell()
  }
}
