//
//  ListCurrencyModels.swift
//  CURRENCY
//
//  Created by Stan Liu on 29/01/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListCurrency {
  // MARK: Use cases

  enum Something {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
}
