//
//  ListCurrencyInteractor.swift
//  CURRENCY
//
//  Created by curry on 2019/04/30.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCurrencyBusinessLogic {
  func doSomething(request: ListCurrency.Something.Request)
}

protocol ListCurrencyDataStore {
  //var name: String { get set }
}

class ListCurrencyInteractor: ListCurrencyBusinessLogic, ListCurrencyDataStore {
  var presenter: ListCurrencyPresentationLogic?
  var worker: ListCurrencyWorker?
  //var name: String = ""

  // MARK: Do something

  func doSomething(request: ListCurrency.Something.Request) {
    worker = ListCurrencyWorker()
    worker?.doSomeWork()

    let response = ListCurrency.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
