//
//  ListBankModels.swift
//  ExchangeHelper
//
//  Created by bryan on 2019/05/02.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListBank {
  // MARK: Use cases
  struct DisplayBankRate: CurrencyBasic, CarryLastUpdate {
    var name: String
    var buy: String
    var sell: String
    var lastUpdate: String
  }

  struct DisplayBank: BankBasic, CarryFee, CarryImageURL {
    var name: String
    var swiftCode: String
    var fee: String
    var imageURL: String?
    var rate: DisplayBankRate
  }
  enum GetList {
    struct Request {
    }
    struct Response {
      var banks: [TWBank.Bank]
    }
    struct ViewModel {
      var displayBanks: [DisplayBank]
      var minBuy: String?
      var maxSell: String?
    }
  }
}

extension Array where Element: StringProtocol {
  func maxx() -> String? {
    guard let max = self.max() else { return nil }
    return String(describing: max)
  }
  func minn() -> String? {
    guard let min = self.min() else { return nil }
    return String(describing: min)
  }
}
