//
//  ListBankInteractor.swift
//  ExchangeHelper
//
//  Created by Meiliang Wen on 22/03/2018.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBankBusinessLogic {
  func getList(request: ListBank.GetList.Request)
}

protocol ListBankDataStore {
  var banks: [TWBank.Bank] { get set }
}

class ListBankInteractor: ListBankBusinessLogic, ListBankDataStore {
  var presenter: ListBankPresentationLogic?
  var worker: ListBankWorker?

  var banks: [TWBank.Bank] = []

  func getList(request: ListBank.GetList.Request) {

    let response = ListBank.GetList.Response(banks: self.banks)
    presenter?.presentList(response: response)
  }
}
