//
//  ListBankRouter.swift
//  ExchangeHelper
//
//  Created by bryan on 2019/05/02.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListBankRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ListBankDataPassing {
  var dataStore: ListBankDataStore? { get }
}

class ListBankRouter: NSObject, ListBankRoutingLogic, ListBankDataPassing {
  weak var viewController: ListBankViewController?
  var dataStore: ListBankDataStore?

  // MARK: Routing

  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation

  //func navigateToSomewhere(source: ListBankViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}

  // MARK: Passing data

  //func passDataToSomewhere(source: ListBankDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
