//
//  ListBankPresenter.swift
//  ExchangeHelper
//
//  Created by bryan on 2019/05/02.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBankPresentationLogic {
  func presentList(response: ListBank.GetList.Response)
}

class ListBankPresenter: ListBankPresentationLogic {
  weak var viewController: ListBankDisplayLogic?

  // MARK: Do something

  func presentList(response: ListBank.GetList.Response) {

    let displayBanks = response.banks.map {
      return ListBank.DisplayBank(name: $0.name,
                                  swiftCode: $0.swiftCode,
                                  fee: $0.fee,
                                  imageURL: $0.imageURL,
                                  rate: ListBank.DisplayBankRate(name: $0.currency.name,
                                                                 buy: $0.currency.buy,
                                                                 sell: $0.currency.sell,
                                                                 lastUpdate: $0.currency.lastUpdate))
    }
    let minBuy = response.banks.map({ return $0.currency.buy }).minn()
    let maxSell = response.banks.map({ return $0.currency.sell }).maxx()
    let viewModel = ListBank.GetList.ViewModel(displayBanks: displayBanks,
                                                  minBuy: minBuy,
                                                  maxSell: maxSell)
    viewController?.displayList(viewModel: viewModel)
  }
}
