//
//  HistoryCurrencyRouter.swift
//  CURRENCY
//
//  Created by Stan Liu on 28/03/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HistoryCurrencyRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  func routeToTWBank(segue: UIStoryboardSegue?)
}

protocol HistoryCurrencyDataPassing {
  var dataStore: HistoryCurrencyDataStore? { get }
}

class HistoryCurrencyRouter: NSObject, HistoryCurrencyRoutingLogic, HistoryCurrencyDataPassing {
  weak var viewController: HistoryCurrencyViewController?
  var dataStore: HistoryCurrencyDataStore?

  // MARK: Routing

  func routeToTWBank(segue: UIStoryboardSegue?) {
    if let segue = segue {
      guard let destinationVC = segue.destination as? TWBankViewController,
        var destinationDS = destinationVC.router!.dataStore,
        let sourceDS = dataStore else { return }

      passDataToTWBank(source: sourceDS, destination: &destinationDS)
    }
  }
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation

  //func navigateToSomewhere(source: HistoryCurrencyViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}

  // MARK: Passing data

  func passDataToTWBank(source: HistoryCurrencyDataStore, destination: inout TWBankDataStore) {
    destination.title = source.name
  }
  //func passDataToSomewhere(source: HistoryCurrencyDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
