//
//  HistoryCurrencyWorker.swift
//  ExchangeHelper
//
//  Created by wang on 2019/04/28.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HistoryCurrencyWorker {
  func getHistory(source: Source,
                  completion: @escaping ([HistoryModelize]?, Error?) -> Void) {
    APIService().history(source: source) { (histories, error) in

      guard let histories = histories else {
        guard let error = error else {
          completion(nil, nil)
          return
        }
        completion(nil, error)
        return
      }
      completion(histories, nil)
    }
  }
}
