//
//  SelectSubjectPresenter.swift
//  ExchangeHelper
//
//  Created by luke on 2019/04/30.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectCurrencyPresentationLogic {
  func presentSources(response: SelectCurrency.SourceOptions.Response)
  func presentCurrencies(response: SelectCurrency.CurrencyOptions.Response)
}

class SelectCurrencyPresenter: SelectCurrencyPresentationLogic {
  weak var viewController: SelectCurrencyDisplayLogic?

  // MARK: Present Sources' option

  func presentSources(response: SelectCurrency.SourceOptions.Response) {

    let viewModel = SelectCurrency.SourceOptions.ViewModel(displaySources: response.sources.map { return $0.name })
    viewController?.displaySources(viewModel: viewModel)
  }

  // Present currencies' option
  func presentCurrencies(response: SelectCurrency.CurrencyOptions.Response) {

    let displayCurrencies = response.currencies
    let viewModel = SelectCurrency.CurrencyOptions.ViewModel(displayCurrencies: displayCurrencies)
    viewController?.displayCurrencies(viewModel: viewModel)
  }
}
