//
//  SelectSubjectModels.swift
//  CURRENCY
//
//  Created by Stan Liu on 21/01/2018.
//  Copyright (c) 2018 Stan Liu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

private protocol SelectCurrencyNameLiteral {
  var name: String { get set }
}

enum SelectCurrency {

  // MARK: Source
  enum SourceOptions {

    struct Request {
    }
    struct Response {
      var sources: [Source]
    }
    struct ViewModel {
      var displaySources: [String]
    }
  }

  // MARK: Currency
  enum CurrencyOptions {

    struct Request {
    }
    struct Response {
      var currencies: [String]
    }
    struct ViewModel {
      var displayCurrencies: [String]
    }
  }
}
