//
//  SelectSubjectInteractor.swift
//  ExchangeHelper
//
//  Created by Meiliang Wen on 21/01/2018.
//  Copyright (c) 2018 Meiliang Wen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectCurrencyBusinessLogic {
  func fetchSources(request: SelectCurrency.SourceOptions.Request)
  func fetchCurrencies(request: SelectCurrency.CurrencyOptions.Request)
}

protocol SelectCurrencyDataStore {
  weak var currencyVC: CurrencyViewController? { get set }
}

class SelectCurrencyInteractor: SelectCurrencyBusinessLogic, SelectCurrencyDataStore {
  var presenter: SelectCurrencyPresentationLogic?
  var worker: CurrencyWorker?
  weak var currencyVC: CurrencyViewController?

  // MARK: fetch Sources' option

  func fetchSources(request: SelectCurrency.SourceOptions.Request) {
    worker = CurrencyWorker()
    //guard let sources = worker?.loadLocalSources() else {
    //  return
    //}
    let sources: [Source] = Source.all
    let response = SelectCurrency.SourceOptions.Response(sources: sources)
    presenter?.presentSources(response: response)
  }

  // fetch currencies' option
  func fetchCurrencies(request: SelectCurrency.CurrencyOptions.Request) {
    worker = CurrencyWorker()
    //guard let sourceName = request.source,
    //  let source = worker?.loadLocalSource(source: sourceName) else {
    //  return
    //}
    let response = SelectCurrency.CurrencyOptions.Response(currencies: Source.Currency.all)
    presenter?.presentCurrencies(response: response)
  }
}
